import clg from "../images/7791868.jpg";

export const arr = [
  {
    cdRank: "#1",
    college: {
      name: "IIT Madras - Indian Institute-(IIMT), Chennai",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "85000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "69000",
      high: "₹1,00,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "5",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 9 More",
    },
  },
  {
    cdRank: "#2",
    college: {
      name: "Parul University, Vadodara",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "95000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "72000",
      high: "₹1,00,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "7",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 6 More",
    },
  },
  {
    cdRank: "#3",
    college: {
      name: "RCCV Girls College, Ghaziabad",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "80000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "88000",
      high: "₹90,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "8.6",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 8 More",
    },
  },
  {
    cdRank: "#4",
    college: {
      name: "KIET Group of Institute, Ghaziabad",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "70000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "60000",
      high: "₹1,00,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "9.2",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 9 More",
    },
  },
  {
    cdRank: "#5",
    college: {
      name: "IIT Madras - Indian Institute-(IIMT), Chennai",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "100000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "82000",
      high: "₹1,00,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "6.3",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 9 More",
    },
  },
  {
    cdRank: "#6",
    college: {
      name: "Example University",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "68000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "80000",
      high: "₹1,00,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "5.5",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 9 More",
    },
  },
  {
    cdRank: "#7",
    college: {
      name: "MMH College",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "50000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "40000",
      high: "₹1,00,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "4.5",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 5 More",
    },
  },
  {
    cdRank: "#8",
    college: {
      name: "Adhunik Group of Institute",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "85000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "80000",
      high: "₹1,00,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "8",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 3 More",
    },
  },
  {
    cdRank: "#9",
    college: {
      name: "Example University",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "85000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "80000",
      high: "₹1,00,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "8.6",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 9 More",
    },
  },
  {
    cdRank: "#10",
    college: {
      name: "Example University",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "85000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "50000",
      high: "₹1,00,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "7.8",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 9 More",
    },
  },
  {
    cdRank: "#11",
    college: {
      name: "Example University",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "85000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "30000",
      high: "₹1,00,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "9.8",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 9 More",
    },
  },
  {
    cdRank: "#12",
    college: {
      name: "Example University",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "85000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "80000",
      high: "₹1,00,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "3",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 9 More",
    },
  },
  {
    cdRank: "#13",
    college: {
      name: "Example University",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "85000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "80000",
      high: "₹1,00,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "8.6",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 9 More",
    },
  },
  {
    cdRank: "#14",
    college: {
      name: "Example University",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "85000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "90000",
      high: "₹150,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "8.6",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 9 More",
    },
  },
  {
    cdRank: "#15",
    college: {
      name: "Example University",
      location: "Chennai, Tamil Nadu",
      logo: <img alt="" src={clg} height={40} width={40} style={{ borderRadius: "50%" }} />,
      field: "B.Tech Computer Science Engineering",
      field2: "JEE-Advanced 2023 Cutoff-144",
    },
    courseFees: {
      amount: "85000",
      course: "Btech",
      yr: "1st Year Fees",
      compare: "Compare Fees",
    },
    placement: {
      avg: "50000",
      high: "₹1,00,000",
      compare: "Compare Placement",
    },
    userReviews: {
      rating: "8.6",
      user: "Based on 300 users",
      review: "Reviews",
      social: "Best in Social Life",
    },
    ranking: {
      rank: "#3rd",
      year: "2023",
      more: "+ 9 More",
    },
  },
];
